# CONEXAO COM O BANCO DE DADOS
spring.datasource.url=jdbc:postgresql://localhost:5432/ccam
spring.datasource.username=postgres
spring.datasource.password=0000

# Configurações do Hibernate (A ferramenta que gerencia as tabelas)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
server.port=8081